# golangci-lint — strict 2026 defaults
run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
